### ISSUE TITLE
Bottom bar break

### ISSUE THREAD

**Issue by farzadi** [dkzwm/SmoothRefreshLayout#28] opened 2017-10-25 13:24 UTC
after using SmoothRefreshLayout my bottom bar break and I cant get why this happened.
![1](https://user-images.githubusercontent.com/3613087/32000922-13182e54-b9a5-11e7-879f-37835d242a7d.jpg)

**Comment by dkzwm** [comment] 2017-10-25 13:34
This lib have no code to set theme  style. You can try to remove SmoothRefreshLayout, in order to find the  reason.

**Comment by dkzwm** [comment] 2017-10-25 13:44
Or,you can set the footer background color to make sure this error is not reason by Footer

**Comment by farzadi** [comment] 2017-10-25 20:02
after removing lib my problem solve. I don't know why this happened. I try both that libraries and I have the same problem.here are links if you want to test it,

https://github.com/roughike/BottomBar
https://github.com/aurelhubert/ahbottomnavigation

here is my XML
```
<me.dkzwm.widget.srl.SmoothRefreshLayout
xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/refreshLayout"
android:layout_width="match_parent"
android:layout_height="match_parent">
<android.support.v7.widget.RecyclerView
    android:id="@+id/recycler_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clipToPadding="false"
    android:scrollbars="vertical" />
</me.dkzwm.widget.srl.SmoothRefreshLayout> 
```

**Comment by dkzwm** [comment] 2017-10-26 02:39
What is the layout of the activity? I can't see the problem from the layout by your offered. I need more information, such as source code、 layout XML.It can be help me to solve you problem.

**Comment by dkzwm** [comment] 2017-10-26 03:45
I have tested the two libraries provided by you. with SmoothRefreshLayout to use the pull up to refresh, but i did not find what you said about this issue.It works well with that libs.

**Comment by farzadi** [comment] 2017-10-26 10:19
just by using me.dkzwm.widget.srl.SmoothRefreshLayout in my layout and without any java code i have same problem.
here is my complete XML:
fragment_ask :
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/fragment_ask"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.farzad.appr.AskFragment">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <Button
            android:id="@+id/fragmnet_ask_filter"
            android:layout_width="60dp"
            android:layout_height="25dp"
            android:layout_gravity="end"
            android:background="@drawable/card_default"
            android:text="Filter"
            android:textColor="@color/colorPrimary"
            android:textSize="14sp"
            android:theme="@style/FilterButtonStyle" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">


            <include layout="@layout/content_main" />

        </RelativeLayout>


    </LinearLayout>


</android.support.design.widget.CoordinatorLayout>

```
content_main:
```

<me.dkzwm.widget.srl.SmoothRefreshLayout
xmlns:android="http://schemas.android.com/apk/res/android"
android:id="@+id/refreshLayout"
android:layout_width="match_parent"
android:layout_height="match_parent">
<android.support.v7.widget.RecyclerView
    android:id="@+id/recycler_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:clipToPadding="false"
    android:scrollbars="vertical" />
</me.dkzwm.widget.srl.SmoothRefreshLayout>
```

**Comment by dkzwm** [comment] 2017-10-26 10:26
Do you mean without `BottomBar/ahbottomnavigation` , but the problem still exists? 
I look the Xml by you provided but i can't see `BottomBar/ahbottomnavigation`.

**Comment by dkzwm** [comment] 2017-10-26 10:42
You can try to switching refresh lib to find the problem, such as `SwipeRefreshLayout`. 
If the problem is caused by the SmoothRefreshLayout, I will try to find the way to solve this issue.

**Comment by farzadi** [comment] 2017-10-26 11:13
No with out this part 
```
mSwipyRefreshLayout = (SwipyRefreshLayout) rootView.findViewById(R.id.swipyrefreshlayout);
        mSwipyRefreshLayout.computeScroll();
        mSwipyRefreshLayout.setColorSchemeColors(COLOR_1, COLOR_2, COLOR_3, COLOR_4);
        mSwipyRefreshLayout.setOnRefreshListener(new SwipyRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh(SwipyRefreshLayoutDirection direction) {
               ...
            }
        });
```

**Comment by dkzwm** [comment] 2017-10-26 11:15
Are you solved the problem?  Is the problem caused by SmoothRefreshLayout?

**Comment by farzadi** [comment] 2017-10-26 11:23
For now, i switching to use this lib :
https://github.com/omadahealth/SwipyRefreshLayout 
with this lib, i don't have any problem and everything work fine.if I find why this has happened, I will tell you.I hope to find why this happened

**Comment by dkzwm** [comment] 2017-10-26 12:23
Can you show me the error log? Your problem is just as shown, the effect looks like three Tab being pressed at the same time,Or have error log？

**Comment by dkzwm** [comment] 2017-10-26 12:30
I really want to know exactly what causes you to say the problem, from my code, I did not have any code on the parent class view, how could such a problem, I am troubled

**Comment by dkzwm** [comment] 2017-10-30 08:41
No feedback, close this issue.

**Closed as completed by dkzwm** 2017-10-30 08:41 UTC

**Comment by dkzwm** [comment] 2017-11-22 02:31
@farzadi  I got a feedback from another issue that might be the cause of your problem. I found that the problem might lie the `onDetachedFromWindow` method has a problem, I removed all message of the handler, that might have removed ripple animations at the same time. 
But I am not sure, so i will release a new version, hope to get your feedback. thx a lot !
